version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    networks:
      - backend_network

  flask_api:
    build: ./flask_api
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:examplepassword@mongodb:27017  # MongoDB connection string
    depends_on:
      - mongodb
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - backend_network

  pokemon_game:
    build: ./pokemon_game  # You can replace this with the correct path to your Dockerfile
    container_name: pokemon_game
    ports:
      - "8080:8080"  # Exposing the port for the game API
    environment:
      FLASK_API_URL: "http://flask_api:5000"  # Use Flask API's container name to access it
    depends_on:
      - flask_api
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
